// 伙伴对谈状态机验证脚本（独立脚本，运行方式见本目录 README）
var failures = 0
func check(_ c: Bool, _ m: String) { if c { print("  ✓ \(m)") } else { print("  ✗ 失败：\(m)"); failures += 1 } }

print("用例1：驻足不足阈值不开口")
var c1 = CompanionConversation()
check(c1.handleStandstill(standstillDurationMs: 2_000, nowMs: 0) == false, "静止 2 秒不征询")
check(c1.handleStandstill(standstillDurationMs: 3_000, nowMs: 0) == true, "静止 3 秒开口征询")
check(c1.stage == .awaitingConsent, "进入等待答复")

print("用例2：接受后走完描述与追问")
var c2 = CompanionConversation()
_ = c2.handleStandstill(standstillDurationMs: 3_000, nowMs: 0)
c2.handleConsent(.accepted, nowMs: 100)
check(c2.stage == .describing, "接受后开始描述")
c2.finishDescribing(nowMs: 5_000)
check(c2.stage == .awaitingFollowUp, "描述完进入追问窗")
c2.handleFollowUp(question: "那家店叫什么？", nowMs: 6_000)
check(c2.stage == .answering, "收到追问进入应答")
check(c2.turns.last?.speaker == .user, "追问已记录")
c2.finishAnswering(nowMs: 9_000)
check(c2.stage == .awaitingFollowUp, "应答完回到追问窗，可继续聊")

print("用例3：拒绝后进入长冷却，期间不再打扰")
var c3 = CompanionConversation()
_ = c3.handleStandstill(standstillDurationMs: 3_000, nowMs: 0)
c3.handleConsent(.declined, nowMs: 1_000)
check(c3.stage == .silent, "拒绝后回到静默")
check(c3.handleStandstill(standstillDurationMs: 10_000, nowMs: 60_000) == false, "1 分钟后仍不打扰")
check(c3.handleStandstill(standstillDurationMs: 10_000, nowMs: 299_000) == false, "不到 5 分钟仍不打扰")
check(c3.handleStandstill(standstillDurationMs: 10_000, nowMs: 301_000) == true, "超过 5 分钟才可再次征询")

print("用例4：征询无人应答，按拒绝处理")
var c4 = CompanionConversation()
_ = c4.handleStandstill(standstillDurationMs: 3_000, nowMs: 0)
check(c4.tick(nowMs: 5_000) == false, "8 秒窗口内不超时")
check(c4.tick(nowMs: 8_000) == true, "超过 8 秒判定无应答")
check(c4.stage == .silent, "回到静默")
check(c4.remainingCooldownMs(nowMs: 8_000) == CompanionConversation.cooldownAfterDeclineMs, "走长冷却")

print("用例5：聊完自然收尾走常规冷却")
var c5 = CompanionConversation()
_ = c5.handleStandstill(standstillDurationMs: 3_000, nowMs: 0)
c5.handleConsent(.accepted, nowMs: 100)
c5.finishDescribing(nowMs: 5_000)
check(c5.tick(nowMs: 21_000) == true, "追问窗 15 秒后超时")
check(c5.remainingCooldownMs(nowMs: 21_000) == CompanionConversation.cooldownAfterSessionMs, "走 60 秒常规冷却，而非长冷却")

print("用例6：描述进行中再次驻足不会打断")
var c6 = CompanionConversation()
_ = c6.handleStandstill(standstillDurationMs: 3_000, nowMs: 0)
c6.handleConsent(.accepted, nowMs: 100)
check(c6.handleStandstill(standstillDurationMs: 9_000, nowMs: 2_000) == false, "描述中不重复征询")
check(c6.stage == .describing, "阶段未被破坏")

print("用例7：使用者中途叫停")
var c7 = CompanionConversation()
_ = c7.handleStandstill(standstillDurationMs: 3_000, nowMs: 0)
c7.handleConsent(.accepted, nowMs: 100)
c7.dismiss(nowMs: 3_000)
check(c7.stage == .silent, "叫停后静默")
check(c7.remainingCooldownMs(nowMs: 3_000) == CompanionConversation.cooldownAfterDeclineMs, "叫停等同拒绝，走长冷却")

print("用例8：主动请求跳过征询直接描述，且不受冷却限制")
var c8 = CompanionConversation()
_ = c8.handleStandstill(standstillDurationMs: 3_000, nowMs: 0)
c8.handleConsent(.declined, nowMs: 1_000)
check(c8.handleManualRequest(nowMs: 2_000) == true, "冷却期内主动请求仍被接受")
check(c8.stage == .describing, "直接进入描述")
c8.finishDescribing(nowMs: 8_000)
check(c8.handleManualRequest(nowMs: 9_000) == false, "追问等待中不重复触发")

print(failures == 0 ? "\n全部通过" : "\n有 \(failures) 项失败")
